export const defaultFocusOutlineClasses = "focus-visible:outline-2 focus-visible:outline-accent-600"
export const focusOutlineInsideClasses = "focus-visible:-outline-offset-2"
export const defaultTransitionClasses = "transition-all duration-100 ease-in-out motion-reduce:transition-none motion-reduce:hover:transition-none"
export const slowTransitionClasses = "transition-all duration-300 ease-in-out motion-reduce:transition-none motion-reduce:hover:transition-none"
export const slowestTransitionClasses = "transition-all duration-700 ease-in-out motion-reduce:transition-none motion-reduce:hover:transition-none"
